events {
    worker_connections 1024;
}

http {
    # Headers
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;

    client_header_buffer_size 16k;
    large_client_header_buffers 4 64k;
    client_max_body_size 100M;

    # SSL Config
    ssl_certificate /etc/nginx/certs/local.crt;
    ssl_certificate_key /etc/nginx/certs/local.key;

    # Web UI
    server {
        listen 3000 ssl;
        location / { proxy_pass http://basyx-aas-web-ui:3000; }
    }
    
    # AAS Environment
    server {
        listen 8081 ssl;
        location / { proxy_pass http://basyx-aas-environment:8081; }
    }
    
    # Keycloak
    server {
        listen 9096 ssl;
        location / { 
            proxy_pass http://keycloak:8080; 
        }
    }
}